kind: Deployment
apiVersion: apps/v1
metadata:
  name: aspdotnet
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspdotnet
      version: v1
  template:
    metadata:
      labels:
        app: aspdotnet
        version: v1
    spec:
      containers:
        - name: container-0
          image: 'aspnetapp:IMAGE_LABEL'
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
              